apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
labels:
  - pairs:
      app.kubernetes.io/name: demo
      app.kubernetes.io/part-of: liveview-assignment
    includeSelectors: true
resources:
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - hpa.yaml
  - pdb.yaml
